source:       .
destination:  ./_site
layouts:      ./_layouts
keep_files:   ['.git','.svn']
exclude:      ['.editorconfig','*.sublime-project','*.sublime-workspace','README.md','CNAME']
timezone:     Europe/Berlin
future:       true
limit_posts:  0
markdown:     redcarpet

name:         "Volker Otto"
title:        "👋 hello @ volkerotto.net"
desc:         "My name is Volker Otto and as a web industry professional with many years of experience, I am currently serving as the CTO @ Digital Masters, where I lead the development of cutting-edge e-commerce and platform solutions for our clients."
url:          "https://volkerotto.net"

paginate:     10
permalink:    pretty

readtime:     true
wpm:          160
